### ISSUE TITLE
Offer Whisper models as options

### ISSUE THREAD

**Issue by 12people** [abb128/april-asr#2]
OpenAI's open-source [Whisper models](https://github.com/openai/whisper) are not only considered by many as state of the art in the FOSS world by many, but also support a range of languages aside from English.

They offer 5 different models at varying file sizes, corresponding to different qualities. It would be nice if at least the "tiny" one was offered as an option.

**Comment by abb128** [comment]
I'm currently not too interested in this as this library is mainly meant for streaming ASR, and Whisper is a non-streaming model at its core. There's techniques to get it to stream but it can end up being computationally expensive and high latency, so I'd rather focus on streaming models for now. If you'd like to use Whisper, there's good alternative options that already work today such as https://github.com/ggerganov/whisper.cpp

**Comment by 12people** [comment]
OK, thanks for the quick reply :)
