### ISSUE TITLE
Installation target in cmake

### ISSUE THREAD

**Issue by TheJackiMonster** [abb128/april-asr#4]
First of all thanks for the great project. I've tested it so far using the English language model and it works great while also having close to none dependencies making it an awesome solution for smaller projects.

I've created a [PKGBUILD](https://aur.archlinux.org/packages/aprilasr-git) script in the AUR to easily install it on Archlinux based systems already which seems to work. The only thing I've noticed is that it likely would work more consistent if there was an `install` target to use with `make install`. So it wouldn't be placed anywhere dependent on such a script.

So maybe you can add something like this at least for the libraries [via cmake](https://cmake.org/cmake/help/latest/command/install.html#command:install).

**Comment by phodina** [comment]
@TheJackiMonster install target was merged in this [commit](https://github.com/abb128/april-asr/commit/b3708aa95c25f2cb3b3e76e74834ce70848296f9)
